### ISSUE TITLE
Basilisk compatibility

### ISSUE THREAD

**Issue by dapgo** [JustOff/ca-archive#10]
After installing "Classic Addon Archive" on Basilisk 201809, and launching it, CA-archive displays the error "Multiprocess mode is not supported now...."

However, Basilisk doesn't support Electrolysis (e10s, multi-process browsing) and check about:support I have
Multiprocess Windows =	0/1 (Disabled)
Any workaround?

**Comment by JustOff** [comment]
Unfortunately, I can't reproduce this problem, CAA works just fine in Basilisk 2018.09.05.

**Comment by dapgo** [comment]
Interesting, after reading your email I tried again and now it is working. 
BTW I was using portable 64bits

**Comment by JustOff** [comment]
I checked both 32/64bit versions before I answered you above. Gremlins?)

**Comment by dapgo** [comment]
Unfortunately, the error is back, i think other extension are impacting on ca-a, si i am checking...

![basilisk_ca-a](https://user-images.githubusercontent.com/4981669/45500698-867f0100-b77f-11e8-9d67-12c71443e7da.png)

**Comment by JustOff** [comment]
Could you provide a screenshot from the processes tab in task manager, sorted by image name and including Basilisk, at the moment when this error occurs?

**Comment by dapgo** [comment]
Sorry for the delay, 
Problem is still the same with latest Basilisk, when following screenshots were taken I was using a  tab group manager with 3 groups and 12 open tabs in total.

![basilisk_processes1](https://user-images.githubusercontent.com/4981669/46478300-f3207500-c7ec-11e8-8e15-4a74780ceda0.png)
![basilisk_processes2](https://user-images.githubusercontent.com/4981669/46478303-f451a200-c7ec-11e8-945d-94ef21ffa281.png)

**Comment by JustOff** [comment]
Your screenshots confirm that you somehow launched the browser in multi-process mode. There should be only one basilisk.exe process.
