### ISSUE TITLE
CAA requires a new hosting

### ISSUE THREAD

**Issue by PotentialTumbleweed** [JustOff/ca-archive#100]
I had migrate to a new Windows laptop, and I installed PM 29.4.0.2
After installing CAA, I tried to download some extensions, such as Saved-Password Buttons. But when I clicked on the "Install Now" button, it returned a 404 error. 
The URL for the button is https://ca-archive.us.to/storage/92/92086/saved_passwords_button-1.2.4-fx.xpi?origin=caa&action=install

I tried several radom extensions, and none of them worked. I either got 404 or a message like this:

File not found

Pale Moon can't find the file at https://cdn.waterfox.net/AMO/xul/60/60265/saved_password_editor-2.10.4-fx+sm+tb.xpi?origin=caa&action=download.

**Comment by JustOff** [comment]
Unfortunately, it happened that the Waterfox CDN can no longer be used as a file storage, so now CAA requires a new hosting.

**Comment by PotentialTumbleweed** [comment]
Why is the Waterfox CDN no longer available for storage?

**Comment by JustOff** [comment]
This is because their new CDN provider no longer supports the configuration necessary to host the CAA storage in its current form.

**Comment by PotentialTumbleweed** [comment]
I wish I could help with that. There are a lot of CDN providers, out there,
though, Maybe Cloudflare ?

**Comment by temp10min** [comment]
@JustOff 
Would it be feasible to add simple torrenting (download only) functionality? This way volunteers could keep the archive in their seedboxes to be used as a fallback when the main hoster is not available. 
Some examples: [magdown ](https://github.com/g4jc/magdown) (it says UXP, but still runs in my NM27; no DHT support) , [WebTorrent](http://www.opennet.ru/opennews/art.shtml?num=43690) (many examples with source in the [FAQ](https://webtorrent.io/faq)), [JStorrent](https://github.com/kzahel/jstorrent).

**Comment by JustOff** [comment]
The full archive of extensions can be downloaded [here](https://archive.org/details/Classic-Add-ons-Archive), but to provide access to individual files, someone should host its content somewhere on the Web.

**Comment by JustOff** [comment]
> I can provide mirror.

It would be great, you will need about 30 GB of space for about 100,000 files from the archive above.

> Too big size for me to download that at one session. 1 GB per archive is would be nice.

  I would recommend you to use the download manager that can resume downloads, such as wget or uget.

**Comment by JeanPaulLucien** [comment]
@JustOff I really can't get this file if nobody creates several archives about 1000 MBs size.

**Comment by temp10min** [comment]
> 
> 
> I really can't get this file if nobody creates several archives about 1000 MBs size.

Use the torrent. 
You can import whatever you have already downloaded and resume from there.

**Comment by temp10min** [comment]
@JustOff 
> 
> 
> It would be great, you will need about 30 GB of space for about 100,000 files from the archive above.

Would it be possible for the extension to extract individual files from that big archive on the fly? Maybe with the help of external index? 
How about if it was repackaged in a ZIP/7z/etc. (non-solid) archive format?

Are you even considering some functionality like this, or you are only interested in a normal web host for the ~100K files?

**Comment by JustOff** [comment]
> Would it be possible for the extension to extract individual files from that big archive on the fly?

No.
 
> are only interested in a normal web host for the ~100K files?

This is the only feasible solution at the moment.

**Comment by Tampa** [comment]
With some offering hosting of the files already might be the best option to simply create a list of mirrors and letting the plugin check which ones are available.

I'd like to sponsor hosting of a mirror as I already host various old stuff for Firefox. On my github profile is a link to my website, you can find contact information there.

**Comment by JustOff** [comment]
I want to express my gratitude to @Tampa and [Zetamex Network](https://zetamex.com/) for providing resources for online file storage!

This issue is now resolved and everything returned to normal operation.

**Comment by SPWGitHub** [comment]
Great! After I bought classic-add-ons.com for 2 years and hosting for it for two years because I was gonna be the hero. Stolen thunder sucks so bad, especially when it costs a yard+.

**Comment by muellert** [comment]
> The full archive of extensions can be downloaded [here](https://archive.org/details/Classic-Add-ons-Archive), but to provide access to individual files, someone should host its content somewhere on the Web.

I'm a bit late to the party, but maybe I can help with mirroring, too, depending on traffic etc.

**Comment by garoto** [comment]
Hosting a HTTP presence for a domain you _bought_ isn't the same thing as hosting+serving content with literally free-bandwidth.

newsflash: bandwidth was never made into a commodity and, still in 2021, can cost a lot of money.

**Comment by SPWGitHub** [comment]
Oh, ya, like millions and millions of people will be clamoring and hammering the entire internet to download hundreds of.xpi files that everyone uses every day! Pfft! Unlimited b/w, unlimited space, very light traffic for this stuff. It doesn't matter, this gives me the excuse I needed to upgrade and migrate anyway.

This actually works out better for me, and If a mirror is desired, I'm happy to provide.

**Comment by garoto** [comment]
I don't get it what you're trying to say. Did you wanted to be first in offering JustOff a box to host the ca-archive and you are  sad now that you missed the opportunity? Very confusing.

**Comment by SPWGitHub** [comment]
Just so happens I have time and money to burn and far better things to do. Cya!

**Comment by garoto** [comment]
Cya!

**Comment by JustOff** [comment]
@SPWGitHub, I'm sorry that your sincere desire to help did not happen in the way you wanted it to be done. It was definitely worth it to contact me first, but I still grate to you for your intentions and wish you good luck in all your endeavors.
