### ISSUE TITLE
Doesn't work in Waterfox Classic 2021.10 (64-bit)

### ISSUE THREAD

**Issue by mark-faulk** [JustOff/ca-archive#101]
When I click the CAA icon, it opens a new tab with "caa:" in the address bar, but the screen says "The address wasn’t understood

Waterfox doesn’t know how to open this address, because one of the following protocols (caa) isn’t associated with any program or is not allowed in this context.

    You might need to install other software to open this address."

**Comment by JustOff** [comment]
I can't reproduce this in a clean profile when CAA is the only installed add-on. In this case, pressing the button opens a new window in the context of the main browser process, and not the tab, as in your case. Perhaps some other extension prevents this.

**Comment by mark-faulk** [comment]
It looks like tab mix plus was blocking it from opening in a new window. I disabled "single window mode" and  CAA works now. Thank you!!
