### ISSUE TITLE
Can't install any addons

### ISSUE THREAD

**Issue by Rajmi105** [JustOff/ca-archive#104]
Server not found

Firefox can’t find the server at ca-archive.us.to.

    Check the address for typing errors such as ww.example.com instead of www.example.com
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

this happens every time when I want to install something

**Comment by JustOff** [comment]
Yes, indeed, the us.to domain began to experience problems with DNS, starting from yesterday. I have already contacted the owner and they said that within 48 hours everything should come back to normal.

**Comment by JustOff** [comment]
It seems everything is back to normal.
