### ISSUE TITLE
caa:list?sort=created does not list the newest

### ISSUE THREAD

**Issue by grahamperrin** [JustOff/ca-archive#11]
1.1.4 with Waterfox 56.2.3 on FreeBSD-CURRENT

### Newest extensions

caa:list?sort=created has (for example) at the head of the list, 

caa:addon/web-health-study

> Released on July 18, 2017

I guess, the link to Newest is redundant.

**Comment by JustOff** [comment]
> caa:list?sort=created has (for example) at the head of the list,
> caa:addon/web-health-study

It really is the most recent *non-Webextension* add-on added to AMO, based on it's [id=832183](https://addons.mozilla.org/en-US/firefox/addon/832183/).

> I guess, the link to Newest is redundant.

This can be useful for historical purposes.

**Comment by grahamperrin** [comment]
Facepalm! Sorry. 

Now I realise why 4.1.6.7 is the latest at caa:addon/lastpass-password-manager/versions and so on.
