### ISSUE TITLE
Server error at zetamex.com

### ISSUE THREAD

**Issue by Ideficks** [JustOff/ca-archive#110]
Always now: "The server at caa.zetamex.com is taking too long to respond."

**Comment by HexagonWin** [comment]
happens for me too. is caa dead now??

**Comment by Ideficks** [comment]
**Online again! Saturday, Dec 10, 2022** 😁👍

**Comment by HexagonWin** [comment]
Wonderful! Thank you.

**Comment by Tampa** [comment]
Apologies, this went under in my notifications. From time to time that machine is under heavy load as it serves a number of large storage pools. If it goes belly up just send me an email, you can find it on the main domain at the bottom :)

**Comment by garoto** [comment]
Thank you for the heads up Tampa.
