### ISSUE TITLE
versions/beta

### ISSUE THREAD

**Issue by grahamperrin** [JustOff/ca-archive#12]
Spun off from https://www.reddit.com/r/waterfox/comments/995urt/-/e507wuu/

> … beta versions and the like … removed from AMO …

https://addons.mozilla.org/addon/lastpass-password-manager/versions/beta (for example) previously listed alpha/beta versions of LastPass, including `https://addons.cdn.mozilla.net/user-media/addons/8542/lastpass_password_manager-4.2.0.8a-an+fx.xpi`, so stepping beyond 

- caa:addon/lastpass-password-manager/versions/

– (nothing more recent than 4.1.67 listed by release 1.1.4 (2018.09) of ca-archive) I experimented: 

- caa:addon/lastpass-password-manager/versions/beta/

No listing. 

----

Please: might a future release of the archive extension – maybe through the integration with Waterfox – gain access to an archive of (at least some of) the versions that Mozilla ceased to serve a few months ago? 

### Retrospective

From [Discontinuing support for beta versions | Mozilla Add-ons Blog](https://blog.mozilla.org/addons/2018/02/28/discontinuing-support-for-beta-versions/) (2018/02/28): 

> … discontinuing support for this feature in the next month. … 

If it helps, compare with https://forums.lastpass.com/viewtopic.php?f=12&t=279075#p991595 (2018-04-03) which observed that at least one of the LastPass betas was still in Mozilla's CDN _more than a month_ after the February blog post.

**Comment by JustOff** [comment]
Sorry, but for a number of reasons CAA will not include beta versions.

**Comment by grahamperrin** [comment]
OK, thanks for clarifying.
