### ISSUE TITLE
Search Engine

### ISSUE THREAD

**Issue by intika** [JustOff/ca-archive#13]
Hello JustOff, 

First thanks a million for this addon, its amazing to see all those data surviving... indeed this will be somehow temporary because devs can not interact with it nor update addon but at least we will keep some very important data... 

The search engine seems to bypass tags and description, when reinstalling my config i find my self searching with AMO instead of CA-A because of the search engine, is it possible easily to include description and tags to searched world, also if possible returning result for any word like AMO search do i know that your search way is better and more correct, but we have more chance to find what we look for with an overloaded result, like AMO do... what do you think ? 

:) :+1:

**Comment by JustOff** [comment]
Yes, currently the search in CAA is very simple, as it's based on the extension name only. I don't think we should consider tags when execute search queries, but searching among descriptions can be really useful.

However, [full-text search](https://www.sqlite.org/fts3.html) requires significant changes in the database and the corresponding functions that I do not have time to do at the moment.

Perhaps someone else could have contributed to this.

**Comment by intika** [comment]
Thanks for your answer :) ... yes indeed we will see later when the AMO storm will start ;) ... may be adding an additional search bar that search in the description in the db... its too early for the moment ^^

**Comment by vanowm** [comment]
It searches by name, but it seems it doesn't separate words by /
For example Back/Forward it considers as one word.

**Comment by JustOff** [comment]
@vanowm, it does not search by words, but only by substring.

**Comment by alreadydone** [comment]
Pale Moon has an add-on site. Would you contact them to see if they'd like
to host these?

JustOff <notifications@github.com> 于 2019年1月12日周六 03:59写道：

**Comment by vanowm** [comment]
sorry, what is substring?

**Comment by intika** [comment]
@JustOff i a currently my opened issue to track my work can you please reopen an other issue for the search engine 
Thanks :) :+1:
