### ISSUE TITLE
xpi file(s) for Add-on Compatibility Reporter – caa:addon/add-on-compatibility-reporter

### ISSUE THREAD

**Issue by grahamperrin** [JustOff/ca-archive#15]
caa:addon/add-on-compatibility-reporter

Maybe a question for @MrAlex94 … please, is `add_on_compatibility_reporter-2.2.4-fx.xpi` amongst the files that will be available to a future release of the Classic Add-ons Archive extension?

### Background

https://addons.mozilla.org/addon/add-on-compatibility-reporter/ was _removed by its author_ a few months ago and AMO ceased to host the `.xpi` files, but 2.2.4 is amongst the releases at https://github.com/mozilla/addon-compatibility-reporter/releases

**Comment by JustOff** [comment]
It will be available. Please have a little patience and soon you will see everything yourself.

**Comment by grahamperrin** [comment]
Thanks, and sorry if I seemed impatient; I'm not.
