### ISSUE TITLE
Legacy version superior to non-legacy version

### ISSUE THREAD

**Issue by grahamperrin** [JustOff/ca-archive#16]
Edge case? 

We have, for example: 

- caa:addon/greasemonkey/versions?page=1#version-3.17
- but not caa:addon/greasemonkey/versions/?page=1#version-4.1

– where: 

- https://addons.mozilla.org/addon/greasemonkey/versions/?page=1#version-4.0 is non-legacy and 
- **a superior version** https://addons.mozilla.org/addon/greasemonkey/versions/?page=1#version-4.1 **is legacy**

**Comment by JustOff** [comment]
> https://addons.mozilla.org/addon/greasemonkey/versions/?page=1#version-4.1 is legacy

No, it's also a WebExtension.

**Comment by grahamperrin** [comment]
Oops. Sorry! Word blindness … it took me months to see the "…and later" part of the line.
