### ISSUE TITLE
Inclusion of 'Add-on home page' links

### ISSUE THREAD

**Issue by grahamperrin** [JustOff/ca-archive#18]
For example, 

- caa:addon/addons-manager-hilite

– includes a link to (404, not found) http://www.shadetreeapiary.com/extension/aomhilite/ that was: 

1. present in October last year at https://web.archive.org/web/20171031052715/https://addons.mozilla.org/en-US/firefox/addon/addons-manager-hilite/
2. not present in July this year at https://web.archive.org/web/20180706032353/https://addons.mozilla.org/en-US/firefox/addon/addons-manager-hilite/

Please: was the rationale to _include a previously given link, if no link was given_ when the database was updated? (That would certainly be reasonable, helpful in many cases.)

Or did I simply stumble across a 404 edge case?

**Comment by JustOff** [comment]
The only data has ever been updated are the new versions of add-ons. For everything else, there's Wayback Machine.
