### ISSUE TITLE
Compatible with Waterfox Android beta v60.1.0esr

### ISSUE THREAD

**Issue by R-OLE** [JustOff/ca-archive#19]
Can't seem to install your v1.2, even when I dig into about:config to override the signing requirement for xpi files.
Can this be fixed with a quick range tweak?

**Comment by ibuprophen1** [comment]
I've got the Waterfox App as well and I receive the following attached (blocked Addon) message as well... 

[blocked-addon-popup](https://user-images.githubusercontent.com/18060271/46584573-03299600-ca33-11e8-817d-f29a0b6490f6.png)


~Ibuprophen

**Comment by JustOff** [comment]
CAA does not support Waterfox for Android.

**Comment by ibuprophen1** [comment]
@JustOff, Can you please explain why? 

You don't have to get into it too elaborately... LOL! :-) 

Also, does it support other Firefox Based browsers like PaleMoon, etc...? 

Thank you! :-) 


~Ibuprophen

**Comment by JustOff** [comment]
See [Compatibility and installation](https://github.com/JustOff/ca-archive#compatibility-and-installation).

**Comment by grahamperrin** [comment]
Also NB [Tor as the base](https://www.reddit.com/r/waterfox/comments/965yk6/currently_testing_the_next_waterfox_for_android/) …

**Comment by R-OLE** [comment]
Alex's response was not very clear at all...

My understanding is that legacy Firefox for Android had either a subset or
a separate API available for its add-ons. It most certainly did have a
selection of add-ons available, as I was using several of them for years,
up until last week on Waterfox!

So, since there were add-ons for legacy Firefox, then is it that
1. the Tor branch Alex is using for his Android Waterfox that has broken
compatibility with older API, or
2. that no one has looked at what is needed to support legacy add-ons for
Android Waterfox, or
3. that no one wants to put any effort into support such add-ons, or
4. those add-ons weren't (yet?) archived with the rest, or
5. Something else I haven't thought of.

If legacy Android add-ons are not made available for Waterfox, it bodes
very poorly for future efforts to tweak/maintain/develop add-ons for that
platform.

If the reason is options 2-4, then I'd suggest thinking about what I said
on Waterfox's issue #757 concerning the importance of support for the
mobile/Android platform.

Regards and thanks for your time and effort spent on this specific project,
and Waterfox in general. And good luck.

On Oct 9, 2018 11:54 PM, "Graham Perrin" <notifications@github.com> wrote:

Also NB Tor as the base
<https://www.reddit.com/r/waterfox/comments/965yk6/currently_testing_the_next_waterfox_for_android/>
…

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/JustOff/ca-archive/issues/19#issuecomment-428429419>,
or mute the thread

**Comment by JustOff** [comment]
At the moment, among the 16,706 add-ons included in CAA, there are 1360 ones that are compatible with both desktop Firefox and Firefox for Android. There are also 162 add-ons that are only compatible with Firefox for Android, but they are not included, although I saved all the necessary data and files.

Honestly, I don't really care about add-ons for the Android version of Firefox or Waterfox, but I can share the saved data if someone decides to deal with them.
