### ISSUE TITLE
Unexpected appearance of foreign text under 'About this Add-on'

### ISSUE THREAD

**Issue by grahamperrin** [JustOff/ca-archive#20]
A minor cosmetic issue. Close _wontfix_, if you like … 

caa:addon/speed-dial

– for example, presents zh-CN (Chinese, simplified) text: 

> 有了Speed Dial，您可以很方便地访问您最常用的网站。要显示Speed Dial标签页，使用Speed Dial按钮（按钮可以添加到工具栏），或在地址栏输入"chrome://speeddial/content"。
> 要指定一个网页到Speed Dial，使用“书签”菜单中新加的“设置为Speed Dial”选项，或右键单击您想要添加的标签页，选择“设置为Speed Dial”。定制工具栏菜单中的这个选项也可用。
> Speed Dial将自动载入到一个新的空白窗口，它也可以载人到新的空白标签页。要配置该项以及其他选项，请使用扩展设置面板。

![2018-10-07 23 17 56 speed dial classic add-ons archive - waterfox](https://user-images.githubusercontent.com/192271/46587653-49a8e000-ca87-11e8-9431-a3dd19b26a9b.png)

The same text is: 

- present at zh-CN https://web.archive.org/web/20181007220513/https://addons.mozilla.org/zh-CN/firefox/addon/speed-dial/
- **not present for en-US** http://web.archive.org/web/20181002210318/https://addons.mozilla.org/en-US/firefox/addon/speed-dial/

**Comment by grahamperrin** [comment]
If it helps – where the most recent en-US capture shows **nothing** in the _About this extension_ area, earlier captures do have the heading, with English text: 

> Direct access to your most visited websites

I haven't gone back through the whole lot to tell whether there was _ever_ Chinese text at the American page, but the English text and heading do appear in these two captures: 

- http://web.archive.org/web/20180913045457/https://addons.mozilla.org/en-US/firefox/addon/speed-dial/
- http://web.archive.org/web/20171014042337/https://addons.mozilla.org/en-US/firefox/addon/speed-dial/ (classic desktop site).

**Comment by JustOff** [comment]
This add-on, like several others, does not contain any description data in the en-US locale. In this case AMO shows nothing or repeats the text from the summary field, but in CAA I decided to use a description from other locale if it's available.

**Comment by grahamperrin** [comment]
This makes sense. Thanks for the explanation.
