### ISSUE TITLE
Attempting to seek '+' results in a search for '%2B' … '&' '%26' … ' …

### ISSUE THREAD

**Issue by grahamperrin** [JustOff/ca-archive#21]
### Example (+)

Seek: 

- Blank Your Monitor + Easy Reading

#### Expected

A single (exact match) search result, 

- caa:addon/blank-your-monitor-easy-readin

#### Actual result

Nothing found, 

- caa:list?q=Blank+Your+Monitor+%2B+Easy+Reading

**Comment by grahamperrin** [comment]
### Example (&)

Seek: 

- Drag & DropZones

### Example (')

Seek: 

- Don't Read The Comments!

**Comment by JustOff** [comment]
Thanks for reporting, resolved by https://github.com/JustOff/ca-archive/commit/9c377143f286319dbc6e248cf01498d64f8e2975. See [CAA 1.2.1b5](https://github.com/JustOff/ca-archive/releases/download/1.2.0/ca-archive-1.2.1b5.xpi).

**Comment by grahamperrin** [comment]
… and I see the more recent commits (thanks), give me maybe half an hour and I should be finished going through my own list. 

I've been editing the additional cases into <https://github.com/JustOff/ca-archive/issues/21#issuecomment-429612559> to sort of minimise noise, would you have preferred each case as a separate brief comment? (Sorry!)

**Comment by JustOff** [comment]
Everything is fine, thanks.

**Comment by grahamperrin** [comment]
OK, I'm done trawling for the day :-)

Tested with 1.2.1b6, re: https://github.com/JustOff/ca-archive/issues/21#issuecomment-429612559 

- the `@` case seems to be fixed
- the other five examples are not found. 

Thanks again!

**Comment by grahamperrin** [comment]
On closer inspection, all good. 

There was some weirdness with bullets and back-ticks in GitHub, for example: 

- `#1 Youtube Video and Mp3 Downloader`

– triple-clicking then copying from that resulted in: 

```text

    #1 Youtube Video and Mp3 Downloader
```

– which, with the white space, was naturally not found. 

I edited https://github.com/JustOff/ca-archive/issues/21#issuecomment-429612559 to **not** use bullet points.

**Comment by JustOff** [comment]
> There was some weirdness with bullets and back-ticks in GitHub

Resolved by https://github.com/JustOff/ca-archive/commit/ef65b7df7401b606d1e6c74789c8746714437d52.
