### ISSUE TITLE
Developerâs Comments ▶ Developer's Comments

### ISSUE THREAD

**Issue by grahamperrin** [JustOff/ca-archive#22]
A minor cosmetic issue. 

At URLs such as these: 

- caa:addon/custom-new-tab
- caa:addon/diigo-web-collector

### Expected

> Developer’s Comments

- with U+2019 (RIGHT SINGLE QUOTATION MARK) as seen in original Mozilla pages

– or, if you prefer (I suggest), an upright apostrophe (U+0027): 

> Developer's Comments

### Actual result

> Developerâs Comments

Copied from the page: `Developerâs Comments`

**Comment by JustOff** [comment]
Thanks for reporting, resolved by https://github.com/JustOff/ca-archive/commit/2dd8bede0fb1b5ea8fb4e050c0354852bbaff754. See [CAA 1.2.1b5](https://github.com/JustOff/ca-archive/releases/download/1.2.0/ca-archive-1.2.1b5.xpi).
