### ISSUE TITLE
Link from somewhere in the Archive to this GitHub repo

### ISSUE THREAD

**Issue by grahamperrin** [JustOff/ca-archive#23]
Unless I'm missing something, there's no link to <https://github.com/JustOff/ca-archive/>.

Maybe add a link from the _About_ page?

caa:about

To https://github.com/JustOff/ca-archive#readme (with the anchor) might be good.

**Comment by JustOff** [comment]
Resolved by https://github.com/JustOff/ca-archive/commit/30ce66d6c6566bc664011afccfb66b842cdf43e8.
