### ISSUE TITLE
Disable Addon Compatibility Checks (Version 4-56)

### ISSUE THREAD

**Issue by grahamperrin** [JustOff/ca-archive#24]
https://addons.mozilla.org/addon/checkcompatibility2/

Just curious, why is this one not in the Archive?

https://addons.mozilla.org/firefox/downloads/file/486878/checkcompatibility2-2.0-tb+fx+sm.xpi

AFAIR: 

- it's never required with recent releases of Waterfox 56.x, but may (in theory) be useful to users of outdated Firefox 56.x
- it serves a very simple purpose, setting a preference.

**Comment by JustOff** [comment]
caa:addon/checkcompatibility2

**Comment by grahamperrin** [comment]
Yeah, I'm puzzled by the discrepancy, 

> Disable Add-on Compatibility Checks (Version 40+)
