### ISSUE TITLE
last version of Automatic Save folder

### ISSUE THREAD

**Issue by pirate486743186** [JustOff/ca-archive#31]
version 1.0.5b of caa:addon/automatic-save-folder
was on the developers site but not on AMO
link inside caa

**Comment by JustOff** [comment]
CAA is an archive, not a live directory.

**Comment by pirate486743186** [comment]
-_-..... it's as alive as some famous parrot...
please read carefully all the lines bellow....

It's a XUL extension, not an updated web extension....
That's no more been developed. From his site.

> Automatic Save folder website is closed
> This project is stopped.
> Thank you for your support so far, but this add-on is not supported anymore.
> I don't have time to update and fix Automatic Save Folder anymore.

On github, the last commit dates back from 2016.....

the last in the archive is 1.0.4
the last on his site is 1.0.5

from caa it self

> Latest version: 1.0.5b129
> PLEASE use the development channel at the bottom of the page to install latest beta version.
> DON'T INSTALL 1.0.4

He said himself, don't install 1.0.4

from caa his site
http://asf.mangaheart.org/
and the extension still there
http://asf.mangaheart.org/automatic_save_folder-1.0.5bRev0129-fx

**Comment by grahamperrin** [comment]
>> … beta …

@pirate486743186 please see https://github.com/JustOff/ca-archive/issues/12#issuecomment-421809898

**Comment by grahamperrin** [comment]
Not found by http://web.archive.org/web/*/http://asf.mangaheart.org/automatic_save_folder-1.0.5bRev0129-fx but there _is_ (now) a Wayback Machine capture at: 

- http://web.archive.org/web/20181121060654/http://asf.mangaheart.org/automatic_save_folder-1.0.5bRev0129-fx

**Comment by pirate486743186** [comment]
from caa it self

>Latest version: 1.0.5b129
>[....]
>DON'T INSTALL 1.0.4

on github, the last commit is named "1.0.5bRev129 (official release)"

the site is still alive, no need of wayback machine....

**Comment by JustOff** [comment]
Sorry, but I simply can't afford to deal with every single version of add-ons that was not published in the AMO.

**Comment by tomasz1986** [comment]
I am not using this particular extension, but in this case the main problem I think is that the last published version is simply broken. As the developer wrote on his website,
>>Mozilla decided to change their add-on system and Automatic Save Folder doesn't work anymore past Firefox v47.
If you still want to use this add-on, you can use this setup :
>>- Firefox ESR (until support for old addon is dropped too)
>>- Latest ASF v1.0.5b revision 129 (signed by mozilla)
