### ISSUE TITLE
Andy Halford's Syncplaces, Sortplaces, Checkplaces would be n.t.h.

### ISSUE THREAD

**Issue by W-Geronius** [JustOff/ca-archive#32]
Andy Halford's Syncplaces (and others) are mirrored on a fan's blog and still work nicely with latest Waterfox. Never found an equal replacement after Andy gave up.

> http://daniel-lange.com/archives/71-SyncPlaces,-SortPlaces-...-preserving-these-and-other-excellent-Firefox-add-ons.html

Would be nice to have those added here
W. Geronius

**Comment by JustOff** [comment]
Unfortunately, since the author deleted these extensions from the AMO many years ago, it seems that their detailed description hasn't been preserved anywhere, and without these it's impossible to add them to CAA.

**Comment by grahamperrin** [comment]
http://web.archive.org/web/20110624030644/https://addons.mozilla.org/en-US/firefox/addon/sortplaces/ information for SortPlaces 1.9.0. 

http://web.archive.org/web/20120519115647/https://addons.mozilla.org/en-US/firefox/addon/checkplaces/ information for CheckPlaces 2.6.2 ("…last original version from Andy…").

**Comment by JustOff** [comment]
> information for SortPlaces 1.9.0
> information for CheckPlaces 2.6.2

Thanks!

**Comment by JustOff** [comment]
tag #43

**Comment by JustOff** [comment]
Resolved by [CAA 2.0.1](https://github.com/JustOff/ca-archive/releases/tag/2.0.1).
