### ISSUE TITLE
video block by lemon rice

### ISSUE THREAD

**Issue by slarlac249** [JustOff/ca-archive#33]
hi, does anyone have or know where to get the last non webextension version
of lemonrices video blocker addon? specifically 5.2.2?

**Comment by JustOff** [comment]
AFAIK, the last non-WebExtension version is 2.0.1 (available in CA Archive).

See [here](https://web.archive.org/web/20161123233400/https://addons.mozilla.org/en-US/firefox/addon/video-blocker/):
> Since version 5.2.2, the add-on is using the new add-on framework called Web Extensions, which is what all Firefox add-ons will be ported to in the (near) future.
