### ISSUE TITLE
Please update for Waterfox 56.2.5

### ISSUE THREAD

**Issue by sharmashivanand** [JustOff/ca-archive#34]
I'm unable to install this addon. I downloaded the zip of the master branch and renamed to xpi. It says "This add-on could not be installed because it appears to be corrupt."

**Comment by JustOff** [comment]
The installation package is located in the [releases](https://github.com/JustOff/ca-archive/releases) section.

**Comment by sharmashivanand** [comment]
Thank you! It works.
