### ISSUE TITLE
Google search link fix

### ISSUE THREAD

**Issue by HarkTu** [JustOff/ca-archive#35]
current page has till v1.5.4, which supports till FF52 and not working at all.
caa:addon/google-search-link-fix

since im using CAA i couldnt think to check AMO for a legacy addon. but somehow i ended there and found newer versions with support FF42+

would be good to add those versions to CAA if possible
thank you for saving those richness, thank you JustOff

**Comment by JustOff** [comment]
Those versions (1.6+) are WebExtensions based, not legacy.
