### ISSUE TITLE
Difficult to use with SeaMonkey

### ISSUE THREAD

**Issue by RainerBielefeld** [JustOff/ca-archive#37]
I observed with unzipped installer of  unofficial (by wg9s) en-US SeaMonkey 2.53 (Windows NT 6.1; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0 Build 20181125130004  (Default Classic Theme, German Language Pack INACTIVE) on German WIN7 64bit:
Simply renaming downloaded .zip to .xpi will not work. When I try to install SM complains "seems to be corrupted". I had to unzip. zip the contained folder ca-archive-master again and to rename it to ca-archive-master.xpi
Installation of that add-on woks fine, new item will be added to menu 'Tools' and clicking that item opens a new TAB in Browser.

**Comment by JustOff** [comment]
As indicated in the [description](https://github.com/JustOff/ca-archive#compatibility-and-installation):

* *The installation package is located in the [releases](https://github.com/JustOff/ca-archive/releases) section*.

**Comment by dirkf** [comment]
Each of ca-archive-1.2.2.xpi, ca-archive-1.2.1.xpi, ca-archive-1.2.0.xpi  is rejected as corrupt by SeaMonkey 2.49.4 (latest stable release).

Also the [Add-On Converter](http://addonconverter.fotokraina.com/) doesn't help.

**Comment by RainerBielefeld** [comment]
@dirkf:  May be you made the same mistake like me, downloaded .zip instead of the .xpi?
Works fine for me, see <https://unofficialseamonkeynews.wordpress.com/tag/ca-archive/>
If my hint did not help, I recommend to discuss your problem with SeaMonkey experts on NG mozilla.support.seamonkey on server “news.mozilla.org” (or the same as [mailing list](https://lists.mozilla.org/listinfo))  or on the [forum](http://forums.mozillazine.org/viewforum.php?f=40&sid=8da4bc9c0df77f19ee7aa448264cd2e4).

**Comment by JustOff** [comment]
@dirkf, try to download XPI locally and install it from a file.

**Comment by dirkf** [comment]
Apparently SM was sick. 1.2.2 installed fine after SM restart and SM found the 1.2.3 update, thx.
