### ISSUE TITLE
Endless database provisioning with SeaMonkey

### ISSUE THREAD

**Issue by RainerBielefeld** [JustOff/ca-archive#38]
I observed with unzipped installer of  unofficial (by wg9s) en-US SeaMonkey 2.53 (Windows NT 6.1; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0 Build 20181125130004  (Default Classic Theme, German Language Pack INACTIVE) on German WIN7 64bit:
After some efforts (see other issue) I was able to install and launch the add-on, but there was no visible progress in 'database provisioning', and SeaMonkey had no visible CPU consumption. So I wonder whether there is a real work being done. Only "dead" web page browser view? https://unofficialseamonkeynews.files.wordpress.com/2019/01/screenshot_database.png

**Comment by JustOff** [comment]
[You have to use the proper installation package](https://github.com/JustOff/ca-archive/issues/37#issuecomment-451753833).
