### ISSUE TITLE
where is passable download local copy of all extensions now (27gb)?

### ISSUE THREAD

**Issue by jen-soft** [JustOff/ca-archive#39]

**Comment by JustOff** [comment]
Sorry, but I do not have the resources to distribute the archive for local use.

**Comment by alreadydone** [comment]
Pale Moon has an add-on site. Would you contact them to see if they'd like to host these?

**Comment by JustOff** [comment]
All classic add-ons previously listed in AMO have been archived and are now available for download using the Classic Add-ons Archive. No one ever promised that they could be downloaded as one large file archive.

**Comment by jabcreations** [comment]
Just create a torrent! Notify everyone who would also be happy to seed. I'd be happy to seed this occasionally.

https://tixati.com/

Additionally in about a year I will be able to provide full and unlimited access to the full archive sans any magnet or torrent links.
