### ISSUE TITLE
Latest version shown at /versions but not at the primary page for an extension

### ISSUE THREAD

**Issue by grahamperrin** [JustOff/ca-archive#40]
caa:addon/fuzzy-time

– defaults to version 1.9, with a blue **Download** button and: 

> Works with Firefox 1.5 - 2.0.0.*

caa:addon/fuzzy-time/versions

– reveals more recent versions, with a green **+ Install Now** button for the latest version. 

### Environment

Waterfox 56.2.6, FreeBSD-CURRENT.

**Comment by grahamperrin** [comment]
Thanks! I can't get my head around things at the moment but 1.2.4b1 does now work for the example in the opening post.

**Comment by JustOff** [comment]
This will be completely resolved by #43.

**Comment by JustOff** [comment]
Resolved by [CAA 2.0.1](https://github.com/JustOff/ca-archive/releases/tag/2.0.1).
