### ISSUE TITLE
CA-archive button disappeared, addon not usable anymore

### ISSUE THREAD

**Issue by mzso** [JustOff/ca-archive#44]
Hi!

The button disappeared from the toolbar. It's not even present in the repository. There's no way to use it anymore. I'm using waterfox
Some more robustness and configurability would be nice. A (configurable) hotkey, for circumstances like this, and I don't like having a button anyway for something that's rarely used and only provides a single feature.
There should be definitely a button to open CAA in about:addons. Either in the main addon's list or CAA's own section.

**Comment by JustOff** [comment]
> The button disappeared from the toolbar. It's not even present in the repository. There's no way to use it anymore. I'm using waterfox

I guess your profile has been corrupted; try to use `Restore Defaults` from `Customize the Menu and Toolbars` to recover it.

> Some more robustness and configurability would be nice. A (configurable) hotkey, for circumstances like this, and I don't like having a button anyway for something that's rarely used and only provides a single feature. There should be definitely a button to open CAA in about:addons. Either in the main addon's list or CAA's own section.

There is already the `Classic Add-ons Archive` item in the `Tools` menu for this case.

**Comment by mzso** [comment]
Thanks. Though I doubt my profile is corrupted. (I wouldn't count out bugs with FF or this or other addons though)

**Comment by mzso** [comment]
Recently I looked into editing xulstore.json and ca-archive-button was there with the rest. I even tried moving it into a different position, but it remained invisible.
