### ISSUE TITLE
Signing the add-on ca-archive.xpi

### ISSUE THREAD

**Issue by guzszisvww** [JustOff/ca-archive#49]
Hello.

Would you please sign the add-on ca-archive-2.0.1.xpi?

P.S. I can turn off the verification of digital signatures. But I think that it is more correct to sign an add-on, and not to disable the verification of digital signatures of add-ons.

Thank.

**Comment by JustOff** [comment]
Unfortunately, this is not possible, since Mozilla more allows to sign add-ons other than WebExtensions.
