### ISSUE TITLE
Maybe support searching for authors or show their addons when clicking their name

### ISSUE THREAD

**Issue by mzso** [JustOff/ca-archive#50]
Hi!

It would be nice if I could check out users other addons. At present when I click on the user name the link takes me to AMO proper, to a most likely empty profile page (since all the classic addons were removed)

It would be neat if I could just click their user name and get a list of their addons as a result.
(Especially if I remember that I want something from that user, but I can't remember the name)

**Comment by JustOff** [comment]
Thanks, this has already been planned in #47.
