### ISSUE TITLE
Can't intall some addons from ca-archive

### ISSUE THREAD

**Issue by decembre** [JustOff/ca-archive#51]
These addons don't want to be installed .
They open tthe "install" pop up but stay frozen at this state:

- <a href="caa:addon/thumbnail-zoom-plus">Thumbnail Zoom Plus 4.2</a>
- <a href="caa:addon/identfavicon">IdentFavIcon 0.3.4.7.1</a>

That's strange because on some of my test profiles "<a href="caa:addon/thumbnail-zoom-plus">Thumbnail Zoom Plus 4.2</a>"
is installed and work perfectly.

I use Waterfox 56.2.8

**Comment by JustOff** [comment]
Sorry, but I can't reproduce this on Waterfox 56.2.8, both extensions are installed correctly.

**Comment by decembre** [comment]
Thanks:
I re tested on a very fresh profile... and yes it work.
Just notice for thumbnail Zoom Plus a little bug:
Instead of its name , there is "nu 4.2l" in the addon manager.
I have that in some other problem too.

But in all other profiles i can't install it.
I don't understand why.
Maybe because i reproduce the same corruption by copy an old profile to a new one?
I tested the fact to reaper one profile and trying to install thumbnail Zoom plus  Not possible .
So, what ?

**Comment by JustOff** [comment]
Please understand that this is an archive of extensions that were originally designed exclusively for Firefox and no one can guarantee their functionality in Waterfox or other browsers. Therefore, all questions regarding the operation of these extensions should be discussed among the users and developers of these add-ons and browsers.

The only case when it makes sense to create issues here is if something is wrong with downloading files or there are other problems with the archive itself.
