### ISSUE TITLE
Google Analytics still active.

### ISSUE THREAD

**Issue by Peacock365** [JustOff/ca-archive#52]
Privacy Badger ver. 2019.2.19 (WebExtension) used in Waterfox 56.2.8 shows the following trackers when browsing the Classic Add-on Archive:

_www.google-analytics.com_
_pagead2.googlesyndication.com_

I know that Mozilla used those trackers to monitor add-on downloads and the general usage of the site, but I think those aren't necessary in Classic Add-on Archive, are they? :-) Probably an oversight, please remove those trackers.

Thank you.

**Comment by JustOff** [comment]
CAA does not use any GA spyware and I can't reproduce your report. Is this observed on specific pages?

**Comment by Peacock365** [comment]
Might(!) be a false positive. In CAA, I wen to the "Most Popular" section, Page 2, FireGestures. Once you have opened the FireGestures add-on page, this link will appear in the description: http://www.xuldev.org/firegestures/ I clicked on the link, then went back to CAA using the "Back" button of the browser. The Google Analytics tracking scripts are still shown thereafter, no matter where I go within the CAA.

This might be a false positive, although I am aware of the fact that Mozilla has used Google Analytics on AMO for quite some time now, so I'd double-check if I were in your shoes.
