### ISSUE TITLE
Better instructions, for getting started

### ISSUE THREAD

**Issue by Andy2No** [JustOff/ca-archive#55]
First of all, thanks - this is a great resource, which I could have done with finding some time ago.

However, having found it, it was not at all obvious, to me, how to use it.  Some simple steps to get started, in the "read me," would have been good.

For others, this is worth reading:

https://www.ghacks.net/2017/11/10/firefox-classic-add-ons-archive/

So,

1) Go to the latest release, and download the .xpi file.

2) Use File->Open, in Waterfox or similar, and browse to where you stored the .xpi.

3) Say yes to allowing it to install.

4) Click the new tool item, which has probably been added to the address bar.  You now have access to a copy of the add-ons site, as it used to be, when it actually worked.

**Comment by JustOff** [comment]
See #45.
