### ISSUE TITLE
to use this , find new entry in EXTRA MENU (waterfox)

### ISSUE THREAD

**Issue by dimyme** [JustOff/ca-archive#56]
Wow! Wow!

You do all the work to collect these nice XPIs then do not bother to drop a single line on how to use it in README where some mega obvious stuff is being said! Moreover, u disabled wiki so no one can add info which u omit. great collection though of course. 

just like 95% of all web techno guys. Took me AGES to find out HTF it works.  This is the documentation ever since "vi" was declared self-explanatory.

### The EXTRA menu has an orange firefox / petals to click then the AMO page opens: "classic add-ons archive"

- you will be able to goto URL   `caa:list/other?sort=name`

and see tons of classic, excellent ADD-ON  ware
please paste and copy if nothing else.

too bad that https://addons.mozilla.org/en-US/firefox/addon/crxviewer/?src=search is not working in CAA only the new AMO as of now.

**Comment by JustOff** [comment]
> The EXTRA menu has an orange firefox / petals to click then the AMO page opens: "classic add-ons archive"

Doesn't a new button appear automatically in the browser panel after you install the extension?

See also #45.

> too bad that https://addons.mozilla.org/en-US/firefox/addon/crxviewer/?src=search is not working in CAA only the new AMO as of now.

It works fine (as well as [Extension Source Explorer](https://github.com/JustOff/esrc-explorer)), just use the context menu on any install and download links.

**Comment by endolith** [comment]
> It works fine (as well as Extension Source Explorer), just use the context menu on any install and download links.

What do you mean by this?  Open the context menu on an install link on https://addons.mozilla.org/?
