### ISSUE TITLE
Re-generate targetApplication info for versions from the actual install.rdf

### ISSUE THREAD

**Issue by mattatobin** [JustOff/ca-archive#57]
Mozilla loved to display compatibility information that was contradictory with what `install.rdf` said in their attempts at compatible-by-default. Largely in regards to `em:maxVersion` but sometimes for `em:minVersion`.

You should work on regenerating the database info for compatibility versions so they match what `install.rdf` actually says at some point.

**Comment by JustOff** [comment]
Yes, it probably makes sense, I will think it over.

**Comment by Lister0fSmeg** [comment]
The max version does not always mean anything. It does not always influence the install and it's ability to go ahead. Go Parent Folder and Show Parent Folder are good examples. Show Parent Folder has a max version of maxVersion="51.0a1 whereas the Mozilla listing in CAA shows 29.0a1.
Go Parent Folder maxversion is 31.0a1 which is shown on the Mozilla extension page for Go Parent Folder. The CAA versions are very slightly earlier versions than the one I am using. Both install without issue on v52.9.1.

**Comment by mattatobin** [comment]
It would still be best if database metadata matched the actual data in install.rdf.

**Comment by JustOff** [comment]
At the moment, I still cannot come to a final opinion on this matter.

**Comment by mattatobin** [comment]
What is there to be opinionated about. AMO DB info doesn't represent the actual files.
