### ISSUE TITLE
Scrape and add Non-webextension based extensions and themes for Thunderbird and SeaMonkey

### ISSUE THREAD

**Issue by mattatobin** [JustOff/ca-archive#58]
It would be really nice if we could preserve the remaining extensions on `addons.thunderbird.net` because either those projects will fail or as time goes on they will have to admit defeat and eventually purge them.

IF NOT for the main extension perhaps a light fork.

I could use my scraping techniques to get the data and xpi files for you if that would be of help. I know it would be a hell of a lot less and given I have the CAA ids I could exclude those you already have that support Phoenix.

**Comment by JustOff** [comment]
To be honest, I'm unlikely to have enough inspiration to do this in the foreseeable future, if at all. Let better someone who is really interested create an independent project or use the full fork of the CAA for this purpose.

**Comment by mattatobin** [comment]
Well I will do a scrape and grab and store it away for someone who wants to implement or create it soon.

**Comment by wyatt8740** [comment]
> Well I will do a scrape and grab and store it away for someone who wants to implement or create a fork soon.

Let me know when this is done; I'd sort of like to take a stab at it.

**Comment by autoteelar** [comment]
did anyone ever scrape the themes? even if they arent in the CAA archive, i only have the default theme. any theme files that work for firefox 52 or basilisk specifically would be appreciated

**Comment by mattatobin** [comment]
I FORGOT.. I stashed my 2018 amo scrape scripts in my scripts repo.. These should still apply to `atbn` as it is olympia before the purge.

You can additionally query the API to get your own list of ids.

**Comment by autoteelar** [comment]
nice! are those 2014 scrapes still available anywhere aswell? 

and yeah, i hope he comes back :)

**Comment by mattatobin** [comment]
The 2014 scripts abused AUS to abuse the discover API .. While it worked well for KNOWN ids.. unknown proved difficult. BUT with all the Pale Moon users we had a good sampling of the most POPULAR ids cause they were being requested for. I sampled those over 48 hours and did the 2014 thing of which I DO have themes. Also some stuff in 2014 wasn't ON amo in 2018 so that is why my earlier effort was important and why I .. eventually... gave it to that crazy Ukrainian gnome to fill out and have at least ONE functioning store which IS the most complete firefox extension archive on this planet.

**Comment by mattatobin** [comment]
Here are directory dumps from my 2014 archive.
[firefox-extensions.txt](https://github.com/JustOff/ca-archive/files/9885005/firefox-extensions.txt)
[firefox-themes.txt](https://github.com/JustOff/ca-archive/files/9885006/firefox-themes.txt)
[firefoxbutnotonamo.txt](https://github.com/JustOff/ca-archive/files/9885007/firefoxbutnotonamo.txt)
[nodata.txt](https://github.com/JustOff/ca-archive/files/9885008/nodata.txt)
[allnotfirefox.txt](https://github.com/JustOff/ca-archive/files/9885009/allnotfirefox.txt)
