### ISSUE TITLE
Crashes  Palemoon.

### ISSUE THREAD

**Issue by Achaean** [JustOff/ca-archive#59]
It installs successfully, but at 1st use, after displaying the message "Performing initial database provisioning..." it stuck and crashes the browser.
With latest Palemoon version (28.5.0) at Win 10 Pro x64 (v.10.0.17763.529).

The workaround that worked for me,  is installing it at Waterfox and downloading the addons from there for installing them at Palemoon.

**Comment by JustOff** [comment]
I can't reproduce this. Does this happen when installed in a new clean profile?

**Comment by Achaean** [comment]
Ooops! Indeed! :-)
It had something to do with a problematic addon.
I got rid of it and now everything's fine.
**THANKS!!!**  :-)
