### ISSUE TITLE
I can't install this add-on……

### ISSUE THREAD

**Issue by nomosaic** [JustOff/ca-archive#61]
Waterfox x64 56.2.12
caa:addon/guiconfig
![guiconfig](https://user-images.githubusercontent.com/14254798/61166685-3e2d9c80-a564-11e9-9404-12c79a61548b.jpg)
Progress bar was stuck.

**Comment by JustOff** [comment]
Sorry, but I can't reproduce this on Waterfox 56.2.12, gui:config 1.10.3 installs just fine.

PS: See also https://github.com/JustOff/ca-archive/issues/51#issuecomment-474064191.
