### ISSUE TITLE
missing Compact Classic theme!

### ISSUE THREAD

**Issue by JimFlasch** [JustOff/ca-archive#63]
Why in the heck do you have the Classic Compact Options add-on in your archive but not the Classic Compact theme it goes with?????????????????????????

Same goes for Noia Fox Options add-on - that too requires a theme you did not bother to include in your archive. Please add these themes so the add-ons can actually be used!

**Comment by JustOff** [comment]
Themes are beyond the scope of this project (#28).

**Comment by JimFlasch** [comment]
Then why include two add-ons that require themes to be useful????????????????
