### ISSUE TITLE
Unable to install in Firefox 53.0.2 - even after toggling xpinstall.signatures.required to false

### ISSUE THREAD

**Issue by Anoneemouse** [JustOff/ca-archive#64]
Firefox won't let me install the add-on, even after I toggled the xpinstall.signatures.required to false.  How do I get a successful install?

**Comment by JustOff** [comment]
[How to disable digital signature verification in Firefox add-ons](https://www.translatetheweb.com/?ref=TVert&from=&to=en&a=https://forum.mozilla-russia.org/viewtopic.php?id=70326).

**Comment by TheLastZombie** [comment]
Doesn't work on Firefox Nightly 72.0a1. Did they change the way signatures are handled (again)? If they did it seems that there aren't any known ways to bypass this at the moment.
