### ISSUE TITLE
Don't see any Search

### ISSUE THREAD

**Issue by Octopod2** [JustOff/ca-archive#65]
NVM

**Comment by Octopod2** [comment]
> title says it.

Not familiar with Github.  Actually, now I don't see the archive at all.

**Comment by JustOff** [comment]
Once you installed [Classic Add-ons Archive](https://github.com/JustOff/ca-archive/releases/latest) there will be an icon in the main browser toolbar and also an item in the "Tools" menu. No additional zip files are required.
