### ISSUE TITLE
Can the archive data be updated with more recent addon versions (e.g. TabMixPlus)?

### ISSUE THREAD

**Issue by Coldblackice** [JustOff/ca-archive#66]
Is there a way to update the archive's snapshot version of an addon?

A popular extension, Tab Mix Plus, has been updated since the time of the archive's snapshot. The archive's snapshot version is 0.5.5.0, but the latest (legacy) version is v0.5.8.1. I'm able to install the latest version manually just fine, I'm just hoping that this would be possible for others out there who can't or don't know to. And for everyone's future reference, wanting us all to have the best possible archive possible.

For reference, here are some links regarding it:

[Main site](https://www.tabmixplus.org/)
[Legacy information](https://tabmixplus.org/support/troubleshooting/data/legacy-tabmix.html)

[Changelog](http://tabmixplus.org/support/viewtopic.php?t=1)

[Recent versions](https://bitbucket.org/onemen/tabmixplus/downloads/)
[Latest version](https://bitbucket.org/onemen/tabmixplus/downloads/tab_mix_plus-0.5.8.1-fx.xpi)

**Comment by JustOff** [comment]
I'm sorry but there is no. CAA is an archive, not a live directory.
