### ISSUE TITLE
Archive search issues

### ISSUE THREAD

**Issue by Coldblackice** [JustOff/ca-archive#67]
The archive's search function is pretty broken -- it not only doesn't do well with any sort of wording/spelling arrangements of addons, but sometimes it doesn't even pull up an addon if it's spelled and worded exactly. When this happens, I'll go to any addon's page (in the archive), and then I'll manually edit the URL with varying word variations until it gets to the addon I'm trying to get to.

Any idea why this isn't working very well?

**Comment by JustOff** [comment]
> it doesn't do well with any sort of wording/spelling arrangements of addons

This is a known issue, see #46

> sometimes it doesn't even pull up an addon if it's spelled and worded exactly

Could you give me an example?
