### ISSUE TITLE
Cannot install addons from Firefox AddOn store anymore

### ISSUE THREAD

**Issue by Lalarian** [JustOff/ca-archive#68]
Hello1

I am Using Waterfox Classic 2019.10 64Bit on Xubuntu 18.04.
Today I wanted to install an AddOn, but I cannot, because the site tells me to install Firefox:
"Only with Firefox—Get Firefox Now".

![WaterfoxBug](https://user-images.githubusercontent.com/5146616/68802884-1445cd00-065f-11ea-9179-48a543eb7ed4.png)

https://addons.mozilla.org/en-US/firefox/addon/save-all-images-webextension/?src=search

**Comment by JustOff** [comment]
This has nothing to do with CAA. [Use the Waterfox support board](https://www.reddit.com/r/waterfox/).

**Comment by Lalarian** [comment]
Oh, sorry, of course not. I am still used to the decades, when internet searches like Google actually found what you where looking for, and not "similar topics"  and so I sometimes blindly follow the first link :(
