### ISSUE TITLE
Small typo...

### ISSUE THREAD

**Issue by Vangelis66** [JustOff/ca-archive#7]
https://github.com/JustOff/ca-archive/blob/ecbc8d2255a407eaa8fe6f3a855ab4cb6a3777fa/content/db.js#L44

`jast` => `just`

Noticed it today by chance, when loading the extension after latest update!
Highly appreciative of your on-going hard efforts to keep the legacy extension ecosystem alive 👍 

Regards

**Comment by JustOff** [comment]
Oops, thanks, it's just a shame for J**u**stOff :smile:
