### ISSUE TITLE
Navigation Toolbar keeps reappearing under PaleMoon

### ISSUE THREAD

**Issue by u3shit** [JustOff/ca-archive#70]
I'm using Pale Moon 28.8.0 under linux (amd64 gentoo), and I've hidden the Navigation Toolbar because I don't use it. Since I installed ca-archive (2.0.1), every time I restart Pale Moon or open a new window, the Navigation Toolbar reappears and I have to hide it again. If I disable this extension, the problem vanishes and the toolbar no longer reappears.

**Comment by JustOff** [comment]
Try [ca-archive-2.0.2b1.xpi](https://github.com/JustOff/ca-archive/releases/download/2.0.1/ca-archive-2.0.2b1.xpi) and set `extensions.ca-archive.unhideToolbar` to `false` in about:config.

**Comment by u3shit** [comment]
I can confirm that it works with that xpi and config (I had to manually create the config value as it didn't exist).

**Comment by JustOff** [comment]
Great, this will be included in the next release.
