### ISSUE TITLE
Exception Errors

### ISSUE THREAD

**Issue by grumpygeek** [JustOff/ca-archive#71]
In both Waterfox Classic 2020.1 and Basilisk (Jan?) on Win 10.  Waterfox was just after following author link to AMO page that didn't exist.  Basilisk error was on first use while or after initializing, but is working after reloading page.  Waterfox crashed but Basilisk didn't.  The errors don't say anything useful, just memory addresses.

I don't have anywhere else to post feedback, but OK to delete/close after reading if you want to.

**Comment by JustOff** [comment]
I can't confirm this, please provide exact steps to reproduce.
