### ISSUE TITLE
Not compatible with Multi-Process 

### ISSUE THREAD

**Issue by Janaue** [JustOff/ca-archive#72]
I have firefox 56 and I could install CCa and launch it, but now I get the window
<img width="321" alt="sshot-2020-02-18-11-51-24" src="https://user-images.githubusercontent.com/10972636/74731600-94746380-5248-11ea-9cda-415e9e0df2f4.png">

I do not know what setting or addon changed it. I used browser.tabs.remote.autostart to false
browser.tabs.remote.autostart1 and browser.tabs.remote.autostart2 to false too but i still have multi-process enabled in about:support

What can check before doing a clean profile?

**Comment by JustOff** [comment]
> `browser.tabs.remote.autostart2`

It should be `browser.tabs.remote.autostart.2`
