### ISSUE TITLE
Can't dl/install any addon

### ISSUE THREAD

**Issue by tazer4** [JustOff/ca-archive#74]
I'm using Waterfox Classic 2020.02.1 x64 and installed the latest .xpi from here for the archive. It lanuches and I can browse the archive but whenever I hit install, it goes to a 404/file not found page for everything from: https://storage-waterfox.netdna-ssl.com/...* and is stuck there, is this on your end or what could the problem be?  Thanks.

**Comment by JustOff** [comment]
Can't reproduce this, any specific example?

**Comment by JustOff** [comment]
Well, the lack of response within 24 hours apparently means that there is no problem.
