### ISSUE TITLE
Connection is not secure

### ISSUE THREAD

**Issue by hawkeye116477** [JustOff/ca-archive#75]
When I want to install some addon, I got `Your connection is not secure`.

**Comment by JustOff** [comment]
Please provide more details.

**Comment by hawkeye116477** [comment]
For example, I type `FlashGot`, click to install and then I'm on `https://ca-archive.biz.tm/storage/0/220/flashgot_mass_downloader-1.5.6.14-fx+sm+tb.xpi?origin=caa&action=install` and got that message.

But if I go just to 'ca-archive.biz.tm/update.xml', then I have a message that This site has been categorized as Malware and Comodo Cybersecurity blocked it (I don't have Comodo of course, that's from site itself).

**Comment by JustOff** [comment]
If you don't have Comodo, then you have MITM, supposedly corporate or provider. The domain itself works just fine, see [SSL Report: ca-archive.biz.tm](https://www.ssllabs.com/ssltest/analyze.html?d=ca-archive.biz.tm&hideResults=on).

**Comment by hawkeye116477** [comment]
Ok, setting Google's DNS helped.
