### ISSUE TITLE
Download blocked by SeaMonkey build in phishing protection

### ISSUE THREAD

**Issue by RainerBielefeld** [JustOff/ca-archive#77]
Steps how to reproduce with installation of unofficial (by wg9s) De SeaMonkey 2.53.2 beta 1 pre Mozilla/5.0  (NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 Build 20200222130008 (Default Classic Theme, newly created User Profile) on German WIN7 64bit and installed *Classic Add-ons Archive* 2.0.1:

1) Launch SeaMonkey  
2) Launch *Classic Add-ons Archive*  
3) Search archive for "plain text links"  
»»» "2 hits appear"  
4) Click "Plain Text Links"  
»»»  "Plain Text Links 1.0.1.1-signed.1-signed" appears  
5) [Download]     
»»» Expected: Download begins  
»»» Actual: Message "Page with unwanted software" 😥  
»»» with a Link to [explication page](https://support.mozilla.org/de/kb/wie-funktioniert-schutz-vor-betrugsversuchen-und-schadprogrammen) (in German for me)

DUP of or related to  #25 ?

I will advertise this issue to developers at mozilla.dev.apps.seamonkey
 
![screenshot_blocking](https://user-images.githubusercontent.com/11803749/78243342-e06f2500-74e3-11ea-8cdb-555e7949e15d.png)

**Comment by JustOff** [comment]
Well, now it was blocked by Google, as usual without any evidence:

![chrome_2020-04-02_15-19-33](https://user-images.githubusercontent.com/340855/78248639-b3c40900-74f5-11ea-9d30-bbcda8a9c8fb.png)

I sent a request to remove the site from their block lists, the rest does not depend on me.

**Comment by RainerBielefeld** [comment]
Ah, I should have read  [explication page](https://support.mozilla.org/de/kb/wie-funktioniert-schutz-vor-betrugsversuchen-und-schadprogrammen) until the end. Thx!

**Comment by JustOff** [comment]
> Review successful for ca-archive.biz.tm
> 
> To: Webmaster of ca-archive.biz.tm,
>
> Google has received and processed your security review request. Google systems indicate that ca-archive.biz.tm no longer contains links to harmful sites or downloads. The warnings visible to users are being removed from your site. This may take a few hours to happen.
