### ISSUE TITLE
Firefox 68esr reports package corrupt

### ISSUE THREAD

**Issue by cengique** [JustOff/ca-archive#78]
I tried installing the 2.0.1 release and the beta packages, but they all end up same. Firefox asks for permission, downloads them, but then gives a message that it could not be installed because the package was corrupt. I already disabled the `xpinstall.signatures.required` config item.

**Comment by JustOff** [comment]
No extension in this archive is designed to work in Firefox ESR 68.

**Comment by cengique** [comment]
Oh, ok. I got it to work on SeaMonkey 2.48. The add-on I was looking for, Scrapbook Plus, didn't work on it, though. It did work on Waterfox Classic 2020-04. Thanks for maintaining this!
