### ISSUE TITLE
Stylus 43.3.1.1 and v1.4.2.3

### ISSUE THREAD

**Issue by Lister0fSmeg** [JustOff/ca-archive#80]
Stylus  43.3.1.1 as included in CAA does not work for me. After install it does not show a toolbar button and is none functional on Cyberfox v52.9.1. The version number seems very strange, 43?

I have Stylus 1.4.23 which works very well for me and does show the toolbar button. Going by the version numbers it is difficult for me to know whether mine is newer than the one in CAA.

If you are interested in the one that I have then I could send you it or attach it if you want.

**Comment by Lister0fSmeg** [comment]
[stylus-1.3.13-an+fx & stylus-1.4.23-fx.zip](https://github.com/JustOff/ca-archive/files/4625870/stylus-1.3.13-an%2Bfx.stylus-1.4.23-fx.zip)
SHA-256: 32E806CBE82085647A03A2C9CCA5C9B6109C1FA25FE6C26B27A8C0062CD88EC7

**Comment by JustOff** [comment]
Stylus 1.3.13 and 1.4.23 are WebExtensions, not classic add-ons.
