### ISSUE TITLE
A few more extension differences, missing or more recent

### ISSUE THREAD

**Issue by Lister0fSmeg** [JustOff/ca-archive#82]
flagfox	more recent version		flagfox5.2.11-esr.xpi
fireshot	missing - works very well	FireShot{0.98.93}.xpi
It is not available on the Moziila site.
https://addons.mozilla.org/en-GB/firefox/addon/fireshot/
I don't care about cookies 2.9.6	more recent version
Enable Right Click and Copy 2017.4.12	missing
AbsoluteEnableRightClickCopy{1.3.4}	missing 1.3.8>
https://addons.mozilla.org/en-GB/firefox/addon/absolute-enable-right-click/versions/
Happy Right-Click 1.1.0	missing
disabled_add_on_fix_for_firefox_52_56-1.1.4.xpi		This is currently available on Mozilla but it is only small and it is worth including. This was referred to as extension Armageddon. Mozilla did not update the security certificate which disabled most extensions.
https://addons.mozilla.org/en-US/firefox/addon/disabled-add-on-fix-52-56/

I have finished installing my Cyberfix extensions and cross checked with CAA and found the above differences. I will leave it there until I know whether you need any of them. A couple are still available ATM from Mozilla. Links provided.

**Comment by JustOff** [comment]
Flagfox 5.2.3 is the latest version published on AMO, and 5.2.11 [is available](https://flagfox.wordpress.com/2018/09/07/september-updates/) from the developer.

As for the rest of the add-ons, I would appreciate if you attach them here so that I can examine them in detail.

**Comment by Lister0fSmeg** [comment]
AbsoluteEnableRightClickCopy{1.3.4}.xpi
absolute_enable_right_click_copy-1.3.8-fx.xpi
EnableRightClickandCopy{2017.4.12}.xpi
FireShot{0.98.93}.xpi
HappyRight-Click{1.1.0}.xpi
Idontcareaboutcookies{2.8.7}.xpi	this looks like it could be a webextenstion
Idontcareaboutcookies{2.8.8}.xpi		"						"
Idontcareaboutcookies{2.9.3}.xpi		"						"
WeatherForecast{0.3.3}.xpi        I do not know about this, I do not remember installing it. It might be a webextension. The version # on CAA looks older but it might not even be the same extension due to being such a common name.

There are some newer versions of Tab Mix Plus available on the TMP website. Those are definitely not webextensions. I downloaded tab_mix_plus-0.5.8.1-fx.xpi very recently.

[Extensions.zip](https://github.com/JustOff/ca-archive/files/4630986/Extensions.zip)
SHA-2565      DFB041956C9C920EA5A943744CB9459FD83C3E499A9E335AC3E116EC24866CA
I am getting a lot of CRC errors on my internet ATM so I recommend verifying the upload.

Are you only including extensions which are not available elsewhere or are you making a more permanent archive of all XUL extensions?

**Comment by JustOff** [comment]
`FireShot{0.98.93}.xpi` can be found at `caa:addon/fireshot`.

All other add-ons from `Extensions.zip` are WebExtenstions.

Only classic add-ons that have ever been published on AMO are included in CAA.

**Comment by Lister0fSmeg** [comment]
Have you tried searching for fireshot? I did and it is not found. The link you providing did show it but searching for the extension name does not find it! If you search for "Full Web Page" or "Full Web Page Screenshots" then it is found. That is not the extension name, therefore it cannot be searching the actual pages, only the title which can miss so much.

**Comment by JustOff** [comment]
In fact, `Full Web Page Screenshots (♥♥♥♥♥)` **is** the only extension name [used on AMO](https://addons.mozilla.org/en-US/firefox/addon/fireshot/), though the search in CAA certainly requires [improvement](https://github.com/JustOff/ca-archive/issues/46).
