### ISSUE TITLE
Invalid security certificate 

### ISSUE THREAD

**Issue by EMH-Mark-I** [JustOff/ca-archive#83]
The `ca-archive.biz.tm` backend domain holds an invalid security certificate.

    ca-archive.biz.tm uses an invalid security certificate.

    The certificate is only valid for the following names:
    *.parkingcrew.net, parkingcrew.net

    (Error code: SSL_ERROR_BAD_CERT_DOMAIN)

![ca-archive](https://user-images.githubusercontent.com/28378002/84843092-9be82580-b00c-11ea-81ad-d5165c3fd585.png)

**Comment by JustOff** [comment]
Yes, something strange happened with the entire `biz.tm` domain, but unfortunately so far I have no information on what exactly happened.

I hope the situation clears up soon, in the worst case, it will take some time to switch to a new domain.

**Comment by JustOff** [comment]
Unfortunately, the worst case scenario was confirmed, I just received an email from the previous biz.tm owner that the domain was sold and will no longer provide public domain registration services.

I will try to switch the archive to the new domain as soon as possible.

**Comment by JustOff** [comment]
The issue is now resolved, but you need to manually install [ca-archive-2.0.2.xpi](https://github.com/JustOff/ca-archive/releases/download/2.0.2/ca-archive-2.0.2.xpi).

**Comment by EMH-Mark-I** [comment]
OK, and thank-you.

**Comment by mattatobin** [comment]
I need a complete copy of the datastore and database of this because it is clear that this slipshot adhoc hosting is likely gonna keep occuring.

**Comment by JustOff** [comment]
Well, it turns out that was not temporary insanity when you recently publicly accused me of not sharing a copy of this archive with you, and you actually managed to lose all the data you received from me on March 7, 2019? Don't you think you should at least apologize before asking me again?

**Comment by mattatobin** [comment]
What data did I loose on March 7th 2019? Also, wasn't I temporarily insane then from a year of overwork?

**Comment by JustOff** [comment]
There was also my answer:

> Re: AMO 2014
> 
> Sent: Thu Mar 07, 2019 12:06 pm
> From: JustOff
> Recipient: New Tobin Paradigm 
> Well, here it is: https://caa.ca-archive.biz.tm/caa20190306.tar.xz
> 
> $ shasum -a 256 caa20190306.tar.xz
> bb7bcb9e9cc44a0ca9731713a634e51fb30231724634c0f11dc5433d78fed053 caa20190306.tar.xz

And a few hours later:

> 68.38.10.xx - - [07/Mar/2019:23:17:12 +0200] "GET /caa20190306.tar.xz HTTP/1.1" 200 15294739676 "https://forum.palemoon.org/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.9) Gecko/20100101 Goanna/4.1 Firefox/60.9 Borealis/1.0.0a1"

**Comment by mattatobin** [comment]
Well if you say it happened it happened. But I don't have that file or a copy of that private message. Must have been lost in the shuffle.

**Comment by VADemon** [comment]
Hi, thanks for fixing this and migrating domains. Is it **a must** to update manually or is it a matter of updating update.xml?

I've run into the issue with [Palemoon](https://forum.palemoon.org/viewtopic.php?p=192701#p192744) and it took me a while to find this repo (there're no on-page mentions or links pointing here). It's just weird to click on the download button and see nothing's happening :)

**Comment by JustOff** [comment]
The need for manual updating to version [2.0.2](https://github.com/JustOff/ca-archive/releases/tag/2.0.2) is caused by the fact that `update.xml` was served through the same `biz.tm` domain, which, after 16 years of acting as a public registry, was suddenly sold to a new owner.

Future updates will come automatically, just as it was before.
