### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by Janaue** [JustOff/ca-archive#86]
Links with waterfox are 404
ex
https://storage-waterfox.netdna-ssl.com/amo/xul/608/608972/youtubetm_auto_pausestop-0.1.0-fx.xpi?origin=caa&action=download
from
caa:addon/youtube-auto-pausestop

same thing for flashgot
https://storage-waterfox.netdna-ssl.com/amo/xul/0/220/flashgot_mass_downloader-1.5.6.14-fx+sm+tb.xpi?origin=caa&action=install

Is the new owner of waterfox interested in maintaining access to all those  XUl addons ?

**Comment by JustOff** [comment]
Can't confirm this, both links works just fine for me.

**Comment by Janaue** [comment]
In my firewall there was a rule blocking 151.139.0.0/16, probably after some list putting it in spam category
