### ISSUE TITLE
RightToClick into catalogue

### ISSUE THREAD

**Issue by Nebula-Mechanica** [JustOff/ca-archive#9]
Maybe add RightToClick (http://web.archive.org/web/20160329174321/https://addons.mozilla.org/en-US/firefox/addon/righttoclick/) into catalogue? Was quite a good extension. Author has removed it from AMO for some reason.

Looks like you can find it here: http://ftp.kr.freebsd.org/pub/ftp.mozilla.org/addons/12572/

By the way @JustOff, consider looking ftp archive above, maybe there will be useful things

**Comment by JustOff** [comment]
Thanks for the suggestion, I'll take it into account in one of the updates.

**Comment by HarkTu** [comment]
Its best right click addon for firefox. I have the last version 2.9.6 if you decide to add it

**Comment by JustOff** [comment]
tag #43

**Comment by JustOff** [comment]
Resolved by [CAA 2.0.1](https://github.com/JustOff/ca-archive/releases/tag/2.0.1).
