### ISSUE TITLE
Can't use the database anymore

### ISSUE THREAD

**Issue by 737simpilot** [JustOff/ca-archive#91]
For a while now it seems that I can't install an extension from the database anymore. Is it still up or what?

**Comment by JustOff** [comment]
Everything is up and running, could you provide the specific link you have problems with?

**Comment by 737simpilot** [comment]
Well, it seems to work in Pale Moon 28.17.0 portable, but not in my Pale Moon 28.16.0 install. Both 32 bit.

I tried to disable all add-ons and used the prefs.js file from the portable version in the install version and still no joy.

**Comment by JustOff** [comment]
Can you reproduce this issue in a clean profile with only CAA installed? If so, please provide the exact steps you are taking.

**Comment by 737simpilot** [comment]
It works in a new profile so I can't reproduce the issue. 

In my default profile if I click the download add-on it just loads and loads.

**Comment by JustOff** [comment]
Unfortunately, as long as everything works in a clean profile and the steps to reproduce the problem are unknown, I can hardly help.

**Comment by 737simpilot** [comment]
Yeah, I think it has something to do with a pref, I'm not sure. I'll leave it as and if I need an old extension I'll just fire up portable PM.
