### ISSUE TITLE
Severe Lag when loading the archive

### ISSUE THREAD

**Issue by OmegaPaladin** [JustOff/ca-archive#92]
I use Pale Moon 29.0.1 and CAA 2.0.3, and I have a lot of lag on accessing the archive.  I do not have this kind of lag even on resource heavy sites like GMail, Outlook, and YouTube.  My browser actually becomes non-responsive for a couple minutes, and even moving my mouse over links there causes lag.  Clicking each link causes a similar lag.  I tried to install a flash video downloader, and I got an error about file being inaccessible - with an address shown in my appdata folder.

**Comment by JustOff** [comment]
Please provide steps to reproduce this issue in a clean profile with only CAA installed.

**Comment by OmegaPaladin** [comment]
Do you have a link to a guide on setting up a second installation or clean profile in Pale Moon?

If this is an addon conflict, are there any addon conflicts you have seen before?  I have manually whitelisted "caa:" on all my installed addons.

**Comment by JustOff** [comment]
> Do you have a link to a guide on setting up a second installation or clean profile in Pale Moon?

What is your OS? On Windows, the easiest way is to use the [portable version](http://www.palemoon.org/download.shtml#Portable_versions).

> If this is an addon conflict, are there any addon conflicts you have seen before?

I don't remember such cases.

**Comment by OmegaPaladin** [comment]
Okay, I did some investigation.  The portable version runs  your addon fine.  It also looks quite different - the version I was running that showed lag shows a tag cloud when you access it, which seems bizarre.

**Comment by JustOff** [comment]
Unfortunately, as long as everything works in a clean profile and the steps to reproduce the problem are unknown, I can hardly help.
