### ISSUE TITLE
Uh, WHERE are the ACTUAL extensions?

### ISSUE THREAD

**Issue by jabcreations** [JustOff/ca-archive#93]
So where are the actual extensions? People keep referencing this project and there are zero extensions here.

**Comment by jabcreations** [comment]
The XPI file apparently contains everything which can be downloaded here:
https://github.com/JustOff/ca-archive/releases

**Comment by jabcreations** [comment]
*sigh*

So this extension just links to an external server...that is down!

Where can I find a ZIP/RAR/etc regardless of it's size that contains the actual original XPI files?

**Comment by JustOff** [comment]
Yes, indeed, today there are problems with the server. I have already contacted the owner and hope everything will be fixed soon.

See also #39.

**Comment by jabcreations** [comment]
Ah, author here! Okay, care to setup a torrent? I'd be happy to seed (provide 100% downloads to others). You'd literally only have to upload the archive once and it could be to several people at the same time. Totally free and I'll be in a position in about a year to provide full free access to the entirety of the archive.

You can setup a torrent (better yet, just a magnet link) using this client:
https://tixati.com/

**Comment by JustOff** [comment]
The CDN issue has been resolved and verified.
