### ISSUE TITLE
Does not work in Waterfox Classic 2021.03 (64-bit)

### ISSUE THREAD

**Issue by mark-faulk** [JustOff/ca-archive#94]
When I try to open Classic Addons Archive in Waterfox Classic 2021.03 (64-bit), all I get is "The address was not understood".

**Comment by JustOff** [comment]
Please provide the steps to reproduce this issue using a new, unmodified browser profile where CAA is the only extension.

**Comment by JustOff** [comment]
The required information is not provided by the reporter.
