### ISSUE TITLE
Show 'list all versions' button instead of install for Pale Moon 29.2 and up

### ISSUE THREAD

**Issue by luciph0r** [JustOff/ca-archive#95]
Since Pale Moon will be blocking installation of extensions not explicitly targeted at it, I'm guessing this will impact CAA as well. Would be good if instead of showing that this extension is not compatible, it just shows the 'list all versions' button so one can manually download the extension and alter it for personal use.

**Comment by TPS** [comment]
Is it possible to go further & patch the included extensions on-the-fly, so they could be directly usable?

**Comment by luciph0r** [comment]
> Is it possible to go further & patch the included extensions on-the-fly, so they could be directly usable?

Wow, you lazy people will do anything to sabotage the project and prevent it from coming out of Firefox's shadow, won't you? Use Waterfox Classic if you're so desperate for a browser that is frozen in time and see it as nothing but a vehicle for extensions that are minimum 4 years and counting out of date.

**Comment by garoto** [comment]
Not sure if joking or...

**Comment by luciph0r** [comment]
> Not sure if joking or...

Not sure who you're referring to when there's a quote option clearly provided :/

**Comment by JustOff** [comment]
1. CAA never shows any add-ons as non-compatible
2. By changing "Install now" to "Download" or "List versions" we will lose information on the level of compatibility
3. You can always use "Save link as…" from the context menu
4. [Moon Tester Tool](https://github.com/JustOff/moon-tester-tool) exists for a reason
