### ISSUE TITLE
Unable to search/install new addons

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [JustOff/ca-archive#96]
Using Waterfox 2021-04.2, when I go to the addon tab via the options menu and enter a search value, the search only looks at my currently installed addons.  How do I get it to search this archive (or what ever the appropriate location is) to install new addons?

Any help is much appreciated. Thanks for keeping this going!

**Comment by JustOff** [comment]
Use `Menu`->`Tolls`->`Classic Add-on Archive` or a toolbar button.
