### ISSUE TITLE
can't open in Waterfox 2021.04.2 (64-bit)

### ISSUE THREAD

**Issue by mark-faulk** [JustOff/ca-archive#97]
When I try to open caa in Waterfox 2021.04.2 (64-bit), it opens a new window with the address of only "caa:" (no domain name/ip address, just "caa:") and says "The Address wasn't understood".

**Comment by JustOff** [comment]
Can you reproduce this issue using a new, unmodified browser profile, where CAA is the only extension?

**Comment by c33s** [comment]
just did a quick test with my waterfox on windows, the `caa` windows still works but my install test failed. tried to install privacy badger and the download timed out. also tried to download with wget.

```
wget https://ca-archive.biz.tm/storage/506/506646/privacy_badger-1.9.2-fx.xpi
--2021-06-01 23:05:23--  https://ca-archive.biz.tm/storage/506/506646/privacy_badger-1.9.2-fx.xpi
Resolving ca-archive.biz.tm (ca-archive.biz.tm)... 144.76.162.245
Connecting to ca-archive.biz.tm (ca-archive.biz.tm)|144.76.162.245|:443... failed: Connection timed out.
```

![image](https://user-images.githubusercontent.com/649209/120389757-219fd680-c32d-11eb-8cda-94bbdc4f9649.png)

![image](https://user-images.githubusercontent.com/649209/120389654-ffa65400-c32c-11eb-868a-f802e5c6f001.png)

**Comment by JustOff** [comment]
@c33s, you need to manually update CAA to [2.0.2+](https://github.com/JustOff/ca-archive/releases), see https://github.com/JustOff/ca-archive/issues/83.

**Comment by c33s** [comment]
manually updated and after about three connection errors the download worked `https://ca-archive.us.to/storage/506/506646/privacy_badger-1.9.2-fx.xpi?origin=caa&action=install`

**Comment by c33s** [comment]
tried with 2.0.2 and 2.0.3 both works 
only having a few connection errors all the time
![image](https://user-images.githubusercontent.com/649209/120392377-ae985f00-c330-11eb-94c8-131122b6aaee.png)

**Comment by JustOff** [comment]
Well, apparently you have some problems with downloading from GitHub, unfortunately I can hardly help with it.

**Comment by JustOff** [comment]
The required information is not provided by the reporter.
